questions:
  0:
    question: "What is the capital of France?"
    type: multiple_choice
    choices:
      - Paris
      - Berlin
      - Rome
    answer: "A"   # Letter corresponding to the correct choice
    duration: 30

  1:
    question: "Is Java statically typed?"
    type: true_or_false
    # choices omitted, implicitly ["True", "False"]
    answer: "True"
    duration: 15

  2:
    question: "Name the inventor of the telephone."
    type: identification
    # No choices for identification
    answer: "Alexander Graham Bell"
    duration: 45