name: OxEventsPlugin
version: 1.0.0
main: me.centauri07.ox.OxEventsPlugin
author: Centauri07
api-version: '1.21.4'
libraries:
  - net.kyori:adventure-text-minimessage:4.22.0
commands:
  event:
    description: Start or join an active event (Trivia, Parkour, Block Hunt).
    usage: |
      /event start <trivia|parkour|block_hunt> <player_limit> <waiting_time>
      /event <join | dolacz>
      /event <leave | opusc>
  eventsetup:
    description: Setup parkour and block hunt event locations and hidden rewards.
    usage: |
      /eventsetup <parkour|block_hunt> <spawn|return>
      /eventsetup parkour <start|end>
      /eventsetup block_hunt hide <rewardKey>